---
title: "Weekly Voter Registration Report"
output: html_notebook
---

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.width=11, fig.height=6}
library(scales)
sumIf <- function(x) {
  val <- ifelse(sum(x)>1, sum(x), NA)
}
leg <- 'Confirmed: Self-Reported (RB); Unknown: Dropped Off; Register: Voter Registration'
ggplot(fileSource, aes(x="", y=n, fill=file)) + 
  geom_bar(stat='identity', width=1) + 
  geom_text(aes(x="",y=pos, label = n), size=5) + 
  coord_polar("y", start=0) +
  theme_minimal() +
  scale_fill_brewer(palette = 'Set2') +
  labs(y='',x='',title=paste0('Total = ',sum(fileSource$n))) +
  scale_y_continuous(breaks=pretty_breaks(5)) +
  theme(
    plot.title = element_text(hjust=.5, size=20),
    legend.title = element_blank(),
    legend.position = "bottom"
    ) 
```

#### Month over Month Pacing

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.width=11, fig.height=6}
ggplot(MoM, aes(x=dayOfMonth, value)) +
  geom_line(aes(color=month)) + 
  labs(title='Voters Registered Month over Month', x='Day of Month', y='Voters Registered') +
  theme(plot.title = element_text(hjust=.5))
```

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.width=12, fig.height=9}
ggplot(MoM.Source, aes(x=dayOfMonth, value)) +
  geom_line(aes(color=month)) + 
  facet_wrap(~source) +
  labs(title='Voters Registered Month over Month by Source', x='Day of Month', y='Voters Registered') +
  theme(plot.title = element_text(hjust=.5))
```

#### Referral Source
```{r warning=FALSE, echo=FALSE, message=FALSE, fig.width=11, fig.height=6}
ggplot(Source, aes(x=status, y=value, fill=reorder(source, value))) +
  geom_bar(stat='identity', position='stack') +
  geom_text(
    position=position_stack(vjust = 0.5), size=3, 
    aes(label=ifelse(value/sum(value)>.01 | (value<1 & value>.02),label,NA))
    ) +
  stat_summary(fun.y = sumIf, aes(label = ..y.., group = status), geom = "text", vjust=-.2) +
  facet_wrap(~variable, scales='free') +
  labs(y='') +
  scale_y_continuous(breaks=pretty_breaks(10)) +
  labs(
    x=leg,
    y='',
    title='Counts and Proportions of Form Status split by Source'
    ) +
  theme(plot.title = element_text(hjust=.5)) + 
  guides(fill=guide_legend(title='Source'))
```
```{r warning=FALSE, echo=FALSE, message=FALSE, fig.width=11, fig.height=6}
ggplot(sourceTime, aes(x=date, y=runningTotal, color=source)) +
  geom_line() + 
  labs(x='Date',y='Registrations',title='Running Total of Registrations by Source') +
  theme(plot.title = element_text(hjust=.5))
```

#### Source Details

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.width=10, fig.height=30}
library(gridExtra)
ss <- split(sourceStep, f=sourceStep$source)
p1 <- ggplot(ss$email, aes(x=status, y=value, fill=reorder(details, value))) +
  geom_bar(stat='identity', position='stack') +
  geom_text(
    position=position_stack(vjust = 0.5), size=3,
    aes(label=ifelse(value/sum(value)>.005 | (value<1 & value>.02),label,NA))
    ) +
  stat_summary(fun.y = sumIf, aes(label = ..y.., group = status), geom = "text", vjust=-.2) +
  scale_y_continuous(breaks=pretty_breaks(10)) +
  facet_wrap(~variable, scales='free')  + 
  labs(x='',y='') +
  theme(plot.title = element_text(hjust=.5)) + 
  guides(fill=guide_legend(title='Source Details'))
p2 <- p1 %+% ss$sms %+% ggtitle('SMS')
p3 <- p1 %+% ss$social %+% ggtitle('Social')
p4 <- p1 %+% ss$web %+% ggtitle('Web')
p1 <- p1 %+% ss$email %+% ggtitle('Email')
p5 <- p1 %+% ss$partner %+% ggtitle('Partner')
grid.arrange(
  p1,p2,p3,p4,p5,ncol=1,
  top='Counts and Proportions of Form Status split by Source and Details',
  bottom=leg
  )

```

#### Northstar Source

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.width=11, fig.height=6}
ggplot(uSource, aes(x=status, y=value, fill=reorder(user_source, value))) +
  geom_bar(stat='identity', position='stack') +
  geom_text(position=position_stack(vjust = 0.5), aes(label=label), size=3) +
  stat_summary(fun.y = sumIf, aes(label = ..y.., group = status), geom = "text", vjust=-.2) +
  facet_wrap(~variable, scales='free') +
  scale_fill_brewer(palette = 'Set2') +
  scale_y_continuous(breaks=pretty_breaks(10)) + 
  labs(
    x=leg,
    y='',
    title='Counts and Proportions of Form Status split by User Source'
    ) +
  theme(plot.title = element_text(hjust=.5)) + 
  guides(fill=guide_legend(title='User Source'))
```

